Repository WhatSong-SG/WhatSong_Frontend, pull requests merged in 2022-06, with the labels that each got.

#16 12 Create WorldCup Game Page
  components/common/Header/index.tsx
  components/common/Header/styles.ts
  components/worldcup/worldcup-final/index.tsx
  components/worldcup/worldcup-final/style.ts
  components/worldcup/worldcup-game/index.tsx
  components/worldcup/worldcup-game/styles.ts
  components/worldcup/worldcup-game/worldcup-game-container/WorldCupTitleData.tsx
  components/worldcup/worldcup-game/worldcup-game-container/index.tsx
  components/worldcup/worldcup-game/worldcup-game-container/style.ts
  components/worldcup/worldcup-game/worldcup-game-main-engine/GameItem.tsx
  components/worldcup/worldcup-game/worldcup-game-main-engine/index.tsx
  components/worldcup/worldcup-game/worldcup-game-main-engine/style.ts
  components/worldcup/worldcup-genre/GenreListItem.tsx
  components/worldcup/worldcup-genre/index.tsx
  components/worldcup/worldcup-genre/styles.ts
  pages/_document.tsx
  pages/tournament/[gener]/final.tsx
  pages/tournament/[gener]/index.tsx
  public/icon/GameImage1.png
  public/icon/Trophy.tsx
  styles/globals.css
Labels: 기능 개발, 퍼블리싱

#18 10 Create Home Page
  components/Card/index.tsx
  components/Card/styles.ts
  components/Carousal/index.tsx
  components/Carousal/styles.ts
  components/Home/index.tsx
  components/Home/styles.ts
  components/common/Header/index.tsx
  components/common/Header/styles.ts
  state/atoms/Global/index.ts
Labels: 기능 개발

#19 17 Development of World Cup Game Pages
  components/worldcup/worldcup-final/index.tsx
  components/worldcup/worldcup-final/style.ts
  components/worldcup/worldcup-game/index.tsx
  components/worldcup/worldcup-game/worldcup-game-container/index.tsx
  components/worldcup/worldcup-game/worldcup-game-main-engine/style.ts
  components/worldcup/worldcup-modal/index.tsx
  module/atom/worldcup/worldcup.ts
  public/icon/Trophy2.svg
  public/icon/index.ts
Labels: 기능 개발, 퍼블리싱

#24 23 homepage api connection
  components/Common/Header/NavModal/index.tsx
  components/Common/Header/index.tsx
  components/Common/Header/styles.ts
  components/Common/Layout/index.tsx
  components/Common/Layout/styles.ts
  components/Home/index.tsx
  components/Home/styles.ts
  interface/Home.ts
  public/assets/AppleMusic.tsx
  public/assets/Facebook.tsx
  public/assets/Spotify.tsx
  public/assets/Twitter.tsx
  public/assets/Youtube.tsx
  public/assets/gray_apple_music.svg
  public/assets/gray_facebook.svg
  public/assets/gray_instagram.svg
  public/assets/gray_spotify.svg
  public/assets/gray_twitter.svg
  public/assets/gray_youtube.svg
  public/assets/index.ts
  utils/api/Home.ts
Labels: 기능 개발, 버그 수정, api 연동

#27 22 Associate World Cup APIs
  components/Gerne/PopSite.tsx
  components/Gerne/styles.tsx
  components/Home/index.tsx
  components/worldcup/worldcup-final/FinalRankLists.tsx
  interface/WorldCup.ts
  utils/api/Worldcup.ts
Labels: api 연동
